# .pre-commit-config.yaml
repos:
  # Black: code formatter (uses your pyproject line-length=100)
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  # Ruff: linter & import sorter (auto-fix easy stuff)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix]

  # Small hygiene fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

# Optional: run pytest automatically on `git push`. Uncomment to enable.
  - repo: local
    hooks:
      - id: pytest
        name: pytest (pre-push)
        entry: pytest -q
        language: system
        pass_filenames: false
        stages: [pre-push]
