[tool.black]
line-length = 100
target-version = ["py310", "py311", "py312"]
exclude = "/(build|dist|\\.venv|\\.git)/"

[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E", "F", "I", "B", "UP", "SIM"]
ignore = ["E203"]  # keep for Black compatibility
exclude = ["build", "dist", ".venv", ".git"]

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["tests"]
